name: tool
description: Runs tests against cloxx interpreter
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies: 
  args: ^2.4.2
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  lints: ^4.0.0
  # test: ^1.24.0
